[build]
  publish = "frontend/out"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_BACKEND_URL_PROD = "https://scoop-ai-backend-production.up.railway.app"
  NEXT_PUBLIC_APP_NAME = "Scoop AI"
  NEXT_PUBLIC_APP_DESCRIPTION = "AI-Powered Social Media Intelligence"
  NEXT_PUBLIC_APP_VERSION = "1.0.0"
  NEXT_PUBLIC_DEBUG_MODE = "false"
  NEXT_PUBLIC_MOCK_DATA_ENABLED = "true"

# Simplified configuration - only essential redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
